asovi_app/urls.py
from django.urls import path

from . import views

app_name = 'asovi_app'
urlpatterns = [
    path('look/<id>/<user>/',views.look,name='look'),
    path('accounts/signup/', views.MySignupView.as_view(), name='account_signup'),
    path('profile_edit/',views.profile_edit,name='profile_edit'),
    path('post/', views.post_view, name='post'),
    path('post_completed/<int:pk>', views.post_completed, name='post_completed'),
    path('change_place/', views.change_place, name='change_place'),
    path('post_detail/<int:pk>/',views.post_detail,name='post_detail'),
    path('post_list/<int:pk>/', views.post_list, name='post_list'),
    path('post_delete/<int:pk>/', views.post_delete, name='post_delete'),
    path('user_profile/<int:pk>/', views.user_profile, name='user_profile'),
    #path('friend_delete/<int:pk>/', views.friend_delete, name='friend_delete'),
    path('friend_request/<int:pk>/', views.friend_request, name='friend_request'),
    path('friend_request_accept/', views.friend_request_accept, name='friend_request_accept'),
    path('friend_list/',views.friend_list, name='friend_list'),
    path('friend_block/<int:pk>/',views.friend_block, name='friend_block'),
    path('post_map/', views.post_map, name='post_map'),
    path('place_search/', views.place_search, name='place_search'),
    path('place_detail/<str:place_id>/', views.place_detail, name='place_detail'),
    path('find_user/', views.FindUserView.as_view(), name='find_user'),
    path('find_user/<int:pk>/', views.FindUserView.as_view(), name='find_user'),
    path('check_event/', views.check_event, name='check_event'),
    path('notification_setting/',views.notification_setting, name='notification_setting'),
    path('my_page/', views.my_page, name='my_page'),
    path('email/change/', views.EmailChange.as_view(), name='change_email'),
    path('email/change/email_sent/', views.change_email_sent, name='change_email_sent'),
    path('email/change/completed/<str:token>/', views.EmailChangeComplete.as_view(), name='change_email_completed'),
    path('id/change/', views.change_id, name='change_id'),
    path('id/change/completed', views.change_id_completed, name='change_id_completed'),
    path('accounts/logout/completed/', views.logout_completed, name='logout_completed'),
    path('signout/', views.signout, name='signout'),
    path('signout/completed/', views.signout_completed, name='signout_completed'),
    path('contact/',views.contact,name='contact'),
    path('save_article/',views.save_article,name='save_article'),
    path('contact_fin/', views.contact_fin, name='contact_fin'),
    path('popular/', views.popular, name='popular'),
    path('settings/', views.settings, name='settings'),
]

asoviva/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('asovi_app.urls')),
    path('accounts/', include('allauth.urls')),
    path('webpush/',include('webpush.urls'))
]

asovi_app/models.py
from django.db.models.deletion import CASCADE, SET_NULL, get_candidate_relations_to_delete
from django.db import models
from django.core.mail import send_mail
from django.contrib.auth.models import PermissionsMixin, UserManager
from django.contrib.auth.base_user import AbstractBaseUser
from django.utils.translation import ugettext_lazy as _
from django.utils import timezone
import re, random, string


class CustomUserManager(UserManager):
    use_in_migrations = True

    def generate_user_id(self, num):
        # <num>文字のランダムな文字列を生成
        return ''.join(random.choices(string.ascii_letters + string.digits, k=num))


    def _create_user(self, email, password, **extra_fields):
        if not email:
            raise ValueError('The given email must be set')
        email = self.normalize_email(email)

        def isHalf(value):
            """
            半角文字(半角カナ以外）かチェック
            user_idが全て半角文字の場合、True
            """
            return re.match(r"^[\x20-\x7E]+$", value) is not None

        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        extra_fields.setdefault('user_id', self.generate_user_id(10))
        return self._create_user(email, password, **extra_fields)


class CustomUser(AbstractBaseUser, PermissionsMixin):

    email = models.EmailField(_('email address'), unique=True)
    first_name = models.CharField(_('first name'), max_length=150, blank=True)
    last_name = models.CharField(_('last name'), max_length=150, blank=True)
    user_id = models.CharField(_('user id'), max_length=50, unique=True)

    is_staff = models.BooleanField(
        _('staff status'),
        default=False,
        help_text=_(
            'Designates whether the user can log into this admin site.'
        )
    )
    is_active = models.BooleanField(
        _('active'),
        default=True,
        help_text=_(
            'Designate whether this user should be treated as active.'
            'Unselect this instead of deleting accounts.'
        ),
    )
    date_joined = models.DateTimeField(_('date joined'), default=timezone.now)

    objects = CustomUserManager()

    EMAIL_FIELD = 'email'
    USERNAME_FIELD = 'email'

    REQUIRED_FIELDS = []

    class Meta:
        verbose_name = _('user')
        verbose_name_plural = _('users')

    def isHalf(value):
        """
        半角文字(半角カナ以外）かチェック
        user_idが全て半角文字の場合、True
        """
        return re.match(r"^[\x20-\x7E]+$", value) is not None

    def get_full_name(self):
        full_name = '%s %s' % (self.first_name, self.last_name)
        return full_name.strip()

    def get_short_name(self):
        return self.first_name

    def email_user(self, subject, message, from_email=None, **kwargs):
        send_mail(subject, message, from_email, [self.email], **kwargs)

    @property
    def username(self):
        return self.email



class Genre(models.Model):
    name = models.CharField(max_length=60)

    class Meta:
        verbose_name_plural = 'genre'

    def __str__(self):
        return self.name


class Profile(models.Model):

    GENDER_CHOICES = [
        (1,'男'),
        (2,'女'),
        (3,'その他'),
    ]

    user = models.OneToOneField(CustomUser,related_name="user_profile",on_delete=CASCADE)
    username = models.CharField(verbose_name='ユーザーネーム',max_length=50)
    icon = models.ImageField(verbose_name='アイコン',upload_to="static/asovi_app/img/",null=True,blank=True)
    introduction = models.TextField(verbose_name='紹介文',null=True,blank=True)
    interested_genre = models.ManyToManyField(Genre,verbose_name='興味のあるジャンル',blank=True)
    gender = models.IntegerField(verbose_name='性別',choices=GENDER_CHOICES,default=0,null=True,blank=True)

    class Meta:
        verbose_name_plural = 'Profile'

    def __str__(self):
        return '<UserProfile:userid=' + str(self.user.id) + ',username=' + self.username + '>'

class NotificationSetting(models.Model):
    user = models.OneToOneField(CustomUser,related_name="user_notification",on_delete=CASCADE)
    good = models.BooleanField(verbose_name='通知設定:いいね',default=True)
    has_saved = models.BooleanField(verbose_name='通知設定:保存',default=True)
    reply = models.BooleanField(verbose_name='通知設定:返信',default=True)
    friend = models.BooleanField(verbose_name='通知設定:フレンドリクエスト',default=True)

    class Meta:
        verbose_name_plural = '通知設定'

# Create y
class Post(models.Model):
    posted_by=models.ForeignKey(CustomUser,related_name='posted_by',on_delete=SET_NULL,null=True)
    image=models.ImageField(upload_to="static/asovi_app/img")
    genre=models.ForeignKey(Genre,related_name='post_genre',on_delete=SET_NULL,null=True,blank=True)
    time=models.DateTimeField(auto_now_add=True,null=True)
    body=models.TextField(max_length=300)
    latitude=models.FloatField()
    longitude=models.FloatField()
    like=models.IntegerField(default=0)
    place_id=models.TextField(null=True)
    place_name=models.TextField(null=True,blank=True)

class Save(models.Model):
    item = models.ForeignKey(Post,on_delete=models.CASCADE)
    person = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    pub_date = models.DateTimeField(auto_now_add=True)
    checked = models.BooleanField(default=False)

class Good(models.Model):
    article = models.ForeignKey(Post,on_delete=models.CASCADE)
    user = models.ForeignKey(CustomUser,on_delete=models.CASCADE)
    good = models.BooleanField(default=False)
    pub_date = models.DateTimeField(auto_now_add=True)
    checked = models.BooleanField(default=False)

class Reply(models.Model):
    post = models.ForeignKey(Post,related_name="post_reply",on_delete=CASCADE)
    posted_by = models.ForeignKey(CustomUser,related_name="user_reply",null=True,on_delete=SET_NULL)
    body = models.TextField(max_length=300)
    pub_date = models.DateTimeField(auto_now_add=True)
    checked = models.BooleanField(default=False)

class Friend(models.Model):
    requestor = models.ForeignKey(CustomUser, related_name='requestor', on_delete=CASCADE)
    requestee = models.ForeignKey(CustomUser, related_name='requestee', on_delete=CASCADE)
    friended = models.BooleanField(default=False)
    requested_date = models.DateTimeField(auto_now_add=True)
    friended_date = models.DateTimeField(blank=True, null=True)
    request_checked = models.BooleanField(default=False)

class Block(models.Model):
    blocker = models.ForeignKey(CustomUser,related_name="blocker",on_delete=CASCADE)
    blocked = models.ForeignKey(CustomUser,related_name="blocked",on_delete=CASCADE)
    block_date = models.DateTimeField(auto_now=True)

class Contact(models.Model):
    contacter=models.ForeignKey(CustomUser,on_delete=CASCADE)
    content=models.TextField(null=False,max_length=500)


class Popular(models.Model):
    num=models.IntegerField()
    place_id=models.CharField(max_length=40,null=True)
    place_name=models.TextField(null=True)

asovi_app/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.core.validators import EmailValidator

from allauth.account.forms import SignupForm
from .models import *


class CustomSignupForm(SignupForm):
    class Meta:
        model = CustomUser
        fields = ['email', 'password']


class ProfileNameForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['username']

class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['username','introduction']
        labels = {
            'username': "名前",
        }

class IDChangeForm(forms.ModelForm):
    class Meta:
        model = CustomUser
        fields = ['user_id']
        labels = {
            'user_id': '新しいユーザーID',
        }


class EmailChangeForm(forms.ModelForm):
    class Meta:
        model = CustomUser
        fields = ['email']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'
            field.widget.attrs['placeholder'] = '新しいメールアドレス'

        def clean_email(self):
            """同じアドレスで仮登録段階のアカウントを消去"""
            email = self.cleaned_data['email']
            CustomUser.objects.filter(email=email, is_active=False).delete()
            try:
                EmailValidator.validate_email(email)
            except ValidationError:
                raise ValidationError('正しいメールアドレスを指定してください。')
            return email

class NotificationForm(forms.ModelForm):
   class Meta:
        model = NotificationSetting
        fields = ['good','has_saved','reply','friend']
        labels = {
           'good': "自分の投稿へのいいねを通知する",
           'has_saved': "自分の投稿が保存されたことを通知する",
           'reply': "自分の投稿への返信を通知する",
           'friend': "自分へのフレンドリクエストを通知する"
        }

class PostForm(forms.ModelForm):
    def __init__(self, *args, **kwd):
        super(PostForm, self).__init__(*args, **kwd)
        self.fields["latitude"].required = False
        self.fields["longitude"].required = False

        self.fields["latitude"].widget.attrs['placeholder'] = '地点を選択して自動入力'
        self.fields["longitude"].widget.attrs['placeholder'] = '地点を選択して自動入力'

    class Meta:
        model = Post
        fields = ['image','body','latitude','longitude','genre']
        labels = {
            'image': "写真",
            'body': "",
            'latitude': "緯度",
            'longitude': "経度",
            'genre': "投稿のジャンル"
        }


class GoodForm(forms.ModelForm):
    class Meta:
        model=Good
        fields=['good']

class SaveForm(forms.Form):
    save=forms.BooleanField(label='Checkbox',required=False)
    model=Post
    fields=['image','body','latitude','longitude']

class FindForm(forms.Form):
    find = forms.CharField(max_length=100, required=False)

class LocationSearchForm(forms.Form):
    radius = [
        (1,'半径200m以内'),
        (2,'半径500m以内'),
        (3,'半径1km以内'),
        (4,'半径2km以内')
    ]
    choice = forms.ChoiceField(label='検索の範囲を指定', choices=radius, widget=forms.RadioSelect(), required=False)

class GenreSearchForm(forms.Form):
    food = forms.BooleanField(label='食事',required=False)
    music = forms.BooleanField(label='音楽',required=False)
    nature = forms.BooleanField(label='自然',required=False)
    art = forms.BooleanField(label='芸術',required=False)
    temple = forms.BooleanField(label='寺社',required=False)
    shopping = forms.BooleanField(label='買物',required=False)
    indoor = forms.BooleanField(label='屋内',required=False)
    outdoor = forms.BooleanField(label='屋外',required=False)
    exercise = forms.BooleanField(label='運動',required=False)

class WordSearchForm(forms.Form):
    key_word = forms.CharField(label='検索:',max_length=50,required=False)


class PlaceSearchForm(forms.Form):
    types = [
        ('none', '指定しない'),
        ('amusement_park', '遊園地'),
        ('aquarium', '水族館'),
        ('art_gallery', '美術館'),
        ('bar', 'バー'),
        ('bowling_alley', 'ボーリング場'),
        ('cafe', 'カフェ'),
        ('campground', 'キャンプ場'),
        ('lodging', '宿泊施設'),
        ('movie_theater', '映画館'),
        ('museum', '博物館'),
        ('park', '公園'),
        ('restaurant', 'レストラン'),
        ('shopping_mall', 'ショッピングセンター'),
        ('spa', '温泉'),
        ('stadium', 'スタジアム'),
        ('store', '店'),
        ('tourist_attraction', '観光名所'),
        ('zoo', '動物園'),
    ]
    radius = forms.IntegerField(label='検索対象の半径', max_value=50000, min_value=0, initial=1000)
    keyword = forms.CharField(label='キーワード', max_length=200, required=False, initial='')
    place_type = forms.MultipleChoiceField(label='カテゴリー', required=False, choices=types, widget=forms.RadioSelect())
    lat = forms.FloatField(label='緯度', required=False, initial=34.987)
    lng = forms.FloatField(label='経度', required=False, initial=135.759)


class ContactForm(forms.ModelForm):
    class Meta:
        model=Contact
        fields=['content']


class SignOutForm(forms.Form):
    email = forms.EmailField(required=True, widget=forms.TextInput(attrs={
        'placeholder': 'メールアドレス',
    }))
    password = forms.CharField(max_length=200, required=True, widget=forms.PasswordInput(attrs={
        'placeholder': 'パスワード',
    }))

asovi_app/templates/asovi_app/post.html
{% load static %}


<!DOCTYPE html>

<html lang="ja">
<head>
  <title>投稿作成</title>
  <link rel="stylesheet" href="{% static 'asovi_app/css/post.css' %}">
  <meta charset="UTF-8">
  <meta name="viewport" content="initial-scale=1.0, user-scalable=no">
  <meta charset="utf-8">
  <style>
    html, body {
      height: 100%;
      margin: 0;
      padding: 0;
    }
    #map {
      height: 80%;
      width: 80%;
    }
  </style>

</head>
   <!-- ここから -->
   <div class="logo">
    <img src="{% static 'asovi_app/img/menuicon.png'%}" alt="" width="18" height="18" class="menutrigger" id="menutrigger">
    <p><strong>投稿作成</strong></p>
    <a href="{% url 'asovi_app:my_page' %}"><img src="{% static 'asovi_app/img/mypageicon.png'%}" alt=""  class="gomypage"></a>
  </div>
  
  <!-- サイドメニュー -->
  <div class="sidemenu hide" id="menubar">
    <ul>
      <!-- <li><a href="{% url 'asovi_app:post' %}">新規投稿作成</a></li> -->
      <li><a href="{% url 'asovi_app:place_search' %}">ホーム</a></li>
      <li><a href="{% url 'asovi_app:popular' %}">人気</a></li>
      <li><a href="{% url 'asovi_app:friend_list' %}">友達</a></li>
      <li><a href="{% url 'asovi_app:find_user' %}">ユーザー検索</a></li>
      <li><a href="{% url 'asovi_app:check_event' %}">通知</a></li>
      <li><a href="{% url 'asovi_app:my_page' %}">マイページ</a></li>
      <li><a href="{% url 'asovi_app:settings' %}">設定</a></li>
      <li><a href="{% url 'account_logout' %}">ログアウト</a></li>
    </ul>
  </div>
  <!-- ここまで共通 -->
  <!-- <div id="map"></div> -->

  <form action="{% url 'asovi_app:post' %}" method="POST" id='latlng' enctype='multipart/form-data'>
    {% csrf_token %}
    <br>
    <div class="imgenre">
      <img src="{% static 'asovi_app/img/cameraicon.png' %}" alt="" id="sampleimg">
      <label id="imgselect">
        <input type="file" accept='image/*' id='selectimg' onchange="previewImage(this);" required name='image'>
      </label>
    </div>
    <br>
    <p class="where">位置情報</p><br>
    <!-- <p class="now"> 現在の地点に基づいた情報です。</p> -->
    <input type="hidden" name="latitude" step="any" required id="id_latitude">
    <input type="hidden" name="longitude" step="any" required id="id_longitude">
    <input type="hidden" name="place_name" id="id_place_name">
    <div id="currentPos">
      {% if place_lat %}
      <p>緯度：{{place_lat}}</p>
      <p>経度：{{place_lng}}</p>
      <p>{{place_name}}</p>
      {% endif %}
    </div>

    <br>
    <p style="margin-top: 27px;">投稿日時</p>
    <p id="today">今日の日付</p>
    <br><br>
    <p>コメント</p><br>
    <textarea name="body" cols="40" rows="10" maxlength="300" required id="id_body" spellcheck="false">{{ body }}</textarea>

    <br>
    <p class="addgenre">ジャンル追加</p>
    <br>
    <div class="genre1">
      <input type="radio" id="expand-toggle01" class="genre-input" name="interested_genre" value="1">
      <label for="expand-toggle01" class="expand-btn">
          食事<img src="{% static 'asovi_app/img/フォークとスプーンのお食事アイコン素材 (1).png' %}" alt="">
        </label>
      <input type="radio" id="expand-toggle02" class="genre-input" name="interested_genre" value="2">
      <label for="expand-toggle02" class="expand-btn">
        音楽<img src="{% static 'asovi_app/img/8分音符アイコン 1 (1).png' %}" alt="">
      </label>
      <input type="radio" id="expand-toggle03" class="genre-input" name="interested_genre" value="3">
      <label for="expand-toggle03" class="expand-btn">
        自然<img src="{% static 'asovi_app/img/登山アイコン4.png' %}" alt=""></label><br>
      </div>
      
      <div class="genre2">
        <input type="radio" id="expand-toggle04" class="genre-input" name="interested_genre" value="4">
        <label for="expand-toggle04" class="expand-btn">
          芸術<img src="{% static 'asovi_app/img/パレットのフリーアイコン7.png' %}" alt=""></label>
          <input type="radio" id="expand-toggle05" class="genre-input" name="interested_genre" value="5">
          <label for="expand-toggle05" class="expand-btn">
            寺社<img src="{% static 'asovi_app/img/シンプルな鳥居アイコン.png' %}" alt=""></label>
      <input type="radio" id="expand-toggle06" class="genre-input" name="interested_genre" value="6">
      <label for="expand-toggle06" class="expand-btn">
          買物<img src="{% static 'asovi_app/img/ショッピングの無料アイコン　3.png' %}" alt=""></label><br>
        </div>
        
  <div class="genre3">
    <input type="radio" id="expand-toggle07" class="genre-input" name="interested_genre" value="7">
      <label for="expand-toggle07" class="expand-btn">
        屋内<img src="{% static 'asovi_app/img/家のアイコン素材.png' %}" alt=""></label>
      <input type="radio" id="expand-toggle08" class="genre-input" name="interested_genre" value="8">
      <label for="expand-toggle08" class="expand-btn">
        屋外 <img src="{% static 'asovi_app/img/自動車の無料アイコン素材 その3 (2).png' %}" alt=""></label>
      <input type="radio" id="expand-toggle09" class="genre-input" name="interested_genre" value="9">
      <label for="expand-toggle09" class="expand-btn">
        運動<img src="{% static 'asovi_app/img/ダッシュのピクトグラム1.png' %}" alt=""></label>
      </div>

      <button type="submit" class="btn btn-secondary submit">投稿</button>
      <div class="space"></div>
      

    </form>
    
  <div class="selectplace">
    
    <input name='getpos' type="button" class="nowhere" value="現在位置を取得" onclick="getPosition();">
    <p class="or">または</p>
    <form action="{% url 'asovi_app:post' %}" method="POST">
      {% csrf_token %}
      <input type="hidden" name="body" id="session_text">
      <a href="{% url 'asovi_app:change_place' %}"><input type="submit" name="change_place" class="place" value="地点の変更" onclick="setSession();"></a>
    </form>
  </div>
  
  
  <script>
    //geolocation apiに関する設定
    if(!navigator.geolocation){
      alert("この端末では位置情報が取得できません");
    }
    var curLat;
    var curLng;
    function getPosition(){
      navigator.geolocation.getCurrentPosition(
        
            function(position){
                curLat = position.coords.latitude;
                curLng = position.coords.longitude;
                // var curLat = 35.0;
                // var curLng = 135.75;
                //var form= document.getElementById('latlng')
                document.getElementById('id_latitude').value = curLat;
                document.getElementById('id_longitude').value = curLng;
                document.getElementById('id_place_name').value = '';
                var latLngShow = document.getElementById('currentPos');
                latLngShow.innerHTML = '';
                var latText = document.createElement("p");
                var lngText = document.createElement("p");
                latText.innerText = "緯度：" + curLat;
                lngText.innerText = "経度：" + curLng;
                latLngShow.appendChild(latText);
                latLngShow.appendChild(lngText);

            },

            function(error) {
                //デバッグ用
                curLat = 35.0;
                curLng = 135.75;
                document.getElementById('id_latitude').value = curLat;
                document.getElementById('id_longitude').value = curLng;
                document.getElementById('id_place_name').value = '';
                var latLngShow = document.getElementById('currentPos');
                var latText = document.createElement("p");
                var lngText = document.createElement("p");
                latLngShow.innerHTML = '';
                latText.innerText = "緯度：" + curLat;
                lngText.innerText = "経度：" + curLng;
                latLngShow.appendChild(latText);
                latLngShow.appendChild(lngText);
                //ここまで
                switch(error.code) {
                    case 1: //PERMISSION_DENIED
                    alert("位置情報の利用が許可されていません");
                    break;
                    case 2: //POSITION_UNAVAILABLE
                    alert("現在位置が取得できませんでした");
                    break;
                    case 3: //TIMEOUT
                    alert("タイムアウトになりました");
                    break;
                    default:
                    alert("その他のエラー(エラーコード:"+error.code+")");
                    break;
                }
            }
        );
    }

    function setSession() {
      document.getElementById('session_text').value = document.getElementById('id_body').value;
    }

    // function initMap() {


    //   var map = new google.maps.Map(document.getElementById('map'), {
    //     zoom: 13,
    //     center: {lat: 35.0030, lng: 135.7674}
    //   });


    //   var marker=new google.maps.Marker({
    //     position: map.getCenter(),
    //     map: map,
    //   });


    //   map.addListener('click', function(e) {
    //     // getClickLatLng(e.latLng, map);
    //     var lat_lng = e.latLng;
    //     var lat1=lat_lng.lat();
    //     var lng1=lat_lng.lng();

    //     document.getElementById('lat').textContent = lat1;
    //     document.getElementById('lng').textContent = lng1;
    //    // console.log(typeof(lat1));


    //    // var form= document.getElementById('latlng');
    //     //form.latitude.value=lat1;
    //     //form.longitude.value=lng1;


    //     var position = { 'lat': lat1, 'lng': lng1};
    //     //console.log(typeof(lat1));
    //     marker.setPosition(position);

    //     var xhr = new XMLHttpRequest();
    //     xhr.open( 'GET', 'https://maps.googleapis.com/maps/api/place/nearbysearch/json?location='+ lat1 +','+ lng1 +'1&radius=50&language=ja&key=AIzaSyCRyLEAaLFtCA4-H10Ie6QOmG9Wi0yiUJk');
    //     xhr.send();
    //     var data = xhr.responseXML;
    //     xhr.addEventListener("load",()=>{
    //       const data = xhr.response
    //       console.log(data)
    //     })



    //     var lat2=data.results.geometry.location.lat;
    //     var lng2=data.results.geometry.location.lng;
    //     var position2={'lat':lat2,'lng':lng2};
    //     marker.setPosition(position2);

    //     var place_id_xhr=data.results.place_id;
    //     var place_name=data.results.name;
    //     document.write(place_name);

    //     var form= document.getElementById('latlng');
    //     form.place_id.value=place_id_xhr;
    //     form.name.value=place_name








    //   });
    // }

    var marker;

    function getClickLatLng(lat_lng, map) {
      var lat1=lat_lng.lat();
      var lng1=lat_lng.lng();

      var form= document.getElementById('latlng');
      form.latitude.value=lat1;
      form.longitude.value=lng1;

      if(marker != null){
        marker.setMap(null);
      }

      marker = new google.maps.Marker({
        position: lat_lng,
        map: map
      });




    }

    // marker = new google.maps.Marker({
    //   position: {
    //     'lat': {{place_lat}},
    //     'lng': {{place_lng}}
    //   },
    //   map: map
    // });

      if( "{{place_lat}}" ){
        var form = document.getElementById('latlng');
        form.latitude.value = "{{place_lat}}";
      }
      if ( "{{place_lng}}" ){
        var form = document.getElementById('latlng');
        form.longitude.value = "{{place_lng}}";
      }
      if ( "{{place_name}}" ){
        var form = document.getElementById('latlng');
        form.place_name.value = "{{place_name}}";
      }

      // 画像選択に関する設定
      function previewImage(obj) {
        var fileReader = new FileReader();
          fileReader.onload = (function(){
          document.getElementById('sampleimg').src = fileReader.result;
        });
        fileReader.readAsDataURL(obj.files[0]);
      }
  </script>
  <!-- 投稿地点の取得 -->
  <!-- <script>
    var a = document.getElementById()
  </script> -->
  <!-- 投稿日時の取得 -->
  <script>
   const now = new Date();
   const year = now.getFullYear();
   const month = now.getMonth();
   const date = now.getDate();

   const output = `${year}/${month + 1}/${date}`;
   document.getElementById('today').textContent = output;
  </script>
   <script>
    document.addEventListener('DOMContentLoaded', function(){
      var trigger = document.getElementById('menutrigger');
      var sidemenu = document.getElementById('menubar');
      // クリックするとサイドバーの開閉
      trigger.addEventListener('click', function(){
          sidemenu.classList.toggle('hide');
      }, false);
    }, false);
    </script>

  <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCRyLEAaLFtCA4-H10Ie6QOmG9Wi0yiUJk&callback=initMap" async defer></script>
</body>
</html>